# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_journal_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='group_name',
            field=models.CharField(max_length=256, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u0433\u0440\u0443\u043f\u0438'),
        ),
    ]
