# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20170904_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='group_name',
        ),
    ]
